### ISSUE TITLE
Can´t create alarm

### ISSUE THREAD

**Issue by Y0ngg4n** [MycroftAI/skill-alarm#100]
```
~~~~oft_skill:on_error:835 | Bei der Verarbeitung der Anfrage ist ein Fehler im Skill Alarm Skill aufgetreten.Traceback (most recent call last):                                                                              
File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper               
handler(message)                                                                                            
File "/opt/mycroft/skills/mycroft-alarm.mycroftai/__init__.py", line 394, in handle_set_alarm                   
today = today[0]                                                                                          
TypeError: 'NoneType' object is not subscriptable         
```

**Comment by krisgesling** [comment]
Thanks for flagging this. I'm assuming you have your language set to something other than English?

There's a fix at the linked PR. Would be great if you had time to test it out :)

**Comment by Y0ngg4n** [comment]
@krisgesling yes i have it set to german. I will try it out these days.
